name: "Assert Branch Naming Convention"
on: pull_request

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          allowed_prefixes: "feat/,bug/"
          ignore: master,develo
